In [90]:
import numpy as np
from sklearn import preprocessing

In [91]:
lexicon = np.array([[1,0,0,0],[0,1,1,1],[0,0,0,1]])
priors = np.array([0.25,0.25,0.25,0.25])
costs = np.array([0,0,0])
alpha = 1

In [92]:
listener_probabilities = np.copy(lexicon)
listener_probabilities = listener_probabilities * priors
listener_probabilities = preprocessing.normalize(listener_probabilities, norm='l1', axis=1)
print(listener_probabilities)

[[1.         0.         0.         0.        ]
 [0.         0.33333333 0.33333333 0.33333333]
 [0.         0.         0.         1.        ]]


In [93]:
speaker_probabilities = np.copy(listener_probabilities)
speaker_probabilities = np.power(speaker_probabilities, 3)
speaker_probabilities = (speaker_probabilities.T * np.exp(-alpha * costs)).T
speaker_probabilities = preprocessing.normalize(speaker_probabilities, norm='l1', axis=0)
print(speaker_probabilities)

[[1.         0.         0.         0.        ]
 [0.         1.         1.         0.03571429]
 [0.         0.         0.         0.96428571]]


In [103]:
def generate_meanings(utterance, offset=0):
    '''Infer the meanings from the world's lexicon.
    input:
    * utterance, an integer, the utterance to infer from

    output: 
    * generated_meanings, a 2D array of boolean, the inferred meanings
    '''
    generated_meanings = []
    if np.any(utterance):
        generated_meanings.append(utterance)
        for i in range(offset,len(utterance)):
            meaning = utterance[i]
            if meaning:
                new_utterance = utterance.copy()
                new_utterance[i] = 0
                generated_meanings.extend(generate_meanings(new_utterance, offset+i))
    return generated_meanings

def generate_lexica(huge_lexicon, incomplete_lexicon=[], offset=0):
    generated_lexica = []
    current_utterance = huge_lexicon[offset]
    current_lexicon = incomplete_lexicon.copy()
    for j, meaning in enumerate(current_utterance):
        if j == 0:
            current_lexicon.append(meaning)
        else:
            current_lexicon[-1] = meaning

        if offset < len(huge_lexicon)-1:
            generated_lexica.extend(generate_lexica(huge_lexicon, current_lexicon, offset+1))
        else:
            generated_lexica.append(current_lexicon)

    return generated_lexica

lexicon = [[1,1],[1,1],[1,1]]
huge_lexicon = []
for i, utterance in enumerate(lexicon):
    huge_lexicon.append(generate_meanings(utterance))
print(huge_lexicon)
lexica = generate_lexica(huge_lexicon)
lexica = np.array(lexica)
print(lexica)

[[[1, 1], [0, 1], [1, 0]], [[1, 1], [0, 1], [1, 0]], [[1, 1], [0, 1], [1, 0]]]
[[[1 1]
  [1 1]
  [1 0]]

 [[1 1]
  [1 1]
  [1 0]]

 [[1 1]
  [1 1]
  [1 0]]

 [[1 1]
  [0 1]
  [1 0]]

 [[1 1]
  [0 1]
  [1 0]]

 [[1 1]
  [0 1]
  [1 0]]

 [[1 1]
  [1 0]
  [1 0]]

 [[1 1]
  [1 0]
  [1 0]]

 [[1 1]
  [1 0]
  [1 0]]

 [[0 1]
  [1 1]
  [1 0]]

 [[0 1]
  [1 1]
  [1 0]]

 [[0 1]
  [1 1]
  [1 0]]

 [[0 1]
  [0 1]
  [1 0]]

 [[0 1]
  [0 1]
  [1 0]]

 [[0 1]
  [0 1]
  [1 0]]

 [[0 1]
  [1 0]
  [1 0]]

 [[0 1]
  [1 0]
  [1 0]]

 [[0 1]
  [1 0]
  [1 0]]

 [[1 0]
  [1 1]
  [1 0]]

 [[1 0]
  [1 1]
  [1 0]]

 [[1 0]
  [1 1]
  [1 0]]

 [[1 0]
  [0 1]
  [1 0]]

 [[1 0]
  [0 1]
  [1 0]]

 [[1 0]
  [0 1]
  [1 0]]

 [[1 0]
  [1 0]
  [1 0]]

 [[1 0]
  [1 0]
  [1 0]]

 [[1 0]
  [1 0]
  [1 0]]]


In [100]:
listener_probabilities = np.copy(lexica)
listener_probabilities = listener_probabilities * priors
for i in range(len(listener_probabilities)):
    listener_probabilities[i] = preprocessing.normalize(listener_probabilities[i], norm='l1', axis=1)
print(listener_probabilities)

[[[1.         0.         0.         0.        ]
  [0.         0.33333333 0.33333333 0.33333333]
  [0.         0.         0.         1.        ]]

 [[1.         0.         0.         0.        ]
  [0.         0.         0.5        0.5       ]
  [0.         0.         0.         1.        ]]

 [[1.         0.         0.         0.        ]
  [0.         0.         0.         1.        ]
  [0.         0.         0.         1.        ]]

 [[1.         0.         0.         0.        ]
  [0.         0.         1.         0.        ]
  [0.         0.         0.         1.        ]]

 [[1.         0.         0.         0.        ]
  [0.         0.5        0.         0.5       ]
  [0.         0.         0.         1.        ]]

 [[1.         0.         0.         0.        ]
  [0.         1.         0.         0.        ]
  [0.         0.         0.         1.        ]]

 [[1.         0.         0.         0.        ]
  [0.         0.5        0.5        0.        ]
  [0.         0.         0. 

In [102]:
for i in range(0):
    print("hello")